<a href="https://colab.research.google.com/github/mustafiz-07/Data/blob/main/kaggle_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv('train_dataset.csv')
df_test=pd.read_csv('test_dataset_exam.csv')

In [ ]:
df.shape

(51952, 25)

In [ ]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [ ]:
features=['Age','Gender','Baggage handling',  'Customer Type','Type of Travel','Class', 'Flight Distance', 'Inflight wifi service','Departure/Arrival time convenient', 'Ease of Online booking','Online boarding', 'Seat comfort','Inflight entertainment','Food and drink', 'On-board service', 'Leg room service','Departure Delay in Minutes', 'Arrival Delay in Minutes']

In [ ]:
df.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             161
satisfaction                           0
dtype: int64

In [ ]:
df_test.isnull().sum()

Unnamed: 0                            0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
dtype: int64

In [ ]:
df.dropna(inplace=True)
df_test['Arrival Delay in Minutes']=df_test['Arrival Delay in Minutes'].fillna(df_test['Arrival Delay in Minutes'].mean())
df_test.isnull().sum()

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
dtype: int64

In [ ]:
df.shape

(51791, 25)

In [ ]:
df_test.shape

(25976, 24)

In [ ]:
X_train=df[features]
X_test=df_test[features]
y_train=df['satisfaction']

In [ ]:
X_train.head()

,Age,Gender,Baggage handling,Customer Type,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Online boarding,Seat comfort,Inflight entertainment,Food and drink,On-board service,Leg room service,Departure Delay in Minutes,Arrival Delay in Minutes
0,28,Female,5,Loyal Customer,Business travel,Business,2586,5,5,5,4,4,4,4,5,2,0,0.0
1,42,Female,4,Loyal Customer,Business travel,Business,507,3,3,3,4,2,4,4,4,4,0,0.0
2,28,Male,2,Loyal Customer,Personal Travel,Eco,113,3,1,3,3,2,2,2,3,2,12,12.0
3,24,Male,3,Loyal Customer,Personal Travel,Business,818,2,5,2,2,3,3,3,3,5,0,6.0
4,45,Male,2,Loyal Customer,Business travel,Business,236,2,5,4,3,3,2,4,2,2,22,26.0

In [ ]:
categorical_cols = ['Type of Travel', 'Class','Gender','Customer Type']

for col in categorical_cols:
  X_train[col] = X_train[col].astype('category').cat.codes
  X_test[col] = X_test[col].astype('category').cat.codes

X_train.tail()

/tmp/ipython-input-239-820416951.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype('category').cat.codes
/tmp/ipython-input-239-820416951.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = X_test[col].astype('category').cat.codes
/tmp/ipython-input-239-820416951.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype('category').cat.codes
/tmp/ipython-input-239-820416951.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = X_test[col].astype('category').cat.codes
/tmp/ipython-input-239-820416951.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype('category').cat.codes
/tmp/ipython-input-239-820416951.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = X_test[col].astype('category').cat.codes
/tmp/ipython-input-239-820416951.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype('category').cat.codes
/tmp/ipython-input-239-820416951.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = X_test[col].astype('category').cat.codes

,Age,Gender,Baggage handling,Customer Type,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Online boarding,Seat comfort,Inflight entertainment,Food and drink,On-board service,Leg room service,Departure Delay in Minutes,Arrival Delay in Minutes
51947,39,1,2,1,0,1,637,3,5,3,3,3,3,3,4,3,1,0.0
51948,17,1,2,0,1,1,646,3,4,3,3,2,3,3,5,1,0,2.0
51949,46,1,3,0,0,1,1197,1,2,2,1,1,4,1,3,3,260,263.0
51950,37,0,4,0,0,1,320,5,5,5,5,5,5,5,1,2,0,0.0
51951,14,0,5,0,1,1,351,4,5,4,4,4,4,4,3,5,0,0.0

In [ ]:

# Create and train the logistic regression model
model = LogisticRegression(max_iter=10000, random_state=42)
model.fit(X_train, y_train)

# Predict on the training set
y_train_pred = model.predict(X_train)

# Predict on the test set
y_test_pred = model.predict(X_test)

# Calculate accuracy on the training set
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f'Accuracy on training set: {train_accuracy}')

Accuracy on training set: 0.8707883609121276

In [ ]:
print(y_test_pred)

['satisfied' 'satisfied' 'neutral or dissatisfied' ...
 'neutral or dissatisfied' 'satisfied' 'neutral or dissatisfied']

In [ ]:


test_predictions_df = pd.DataFrame({'ID': df_test['id'], 'satisfaction': y_test_pred})


print(test_predictions_df.head())

      ID             satisfaction
0  19556                satisfied
1  90035                satisfied
2  12360  neutral or dissatisfied
3  77959  neutral or dissatisfied
4  36875  neutral or dissatisfied

In [ ]:
test_predictions_df.to_csv('test_predictions.csv', index=False)

In [ ]:
from google.colab import files

In [ ]:
files.download('test_predictions.csv')

In [ ]:
y_test_pred.shape

(25976,)